### ISSUE TITLE
[Feature request] Notification without kicking

### ISSUE THREAD

**Issue by liquidman228** [RageOfFire/ROF_AntiVPN#1]
I posted this on spigotmc before, but there was no response

Can you add a feature so that the plugin only sends a webhook but doesn't kick the player?

That would be very helpful, thanks

**Comment by RageOfFire** [comment]
Hi ! Thank for the feature request ! I will make it available in the next update.

**Comment by liquidman228** [comment]
Thank you, I'll be waiting! Because manually checking every IP through this API is quite difficult, lol
